pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2:z -u root'
        }
    }
        options {
        skipStagesAfterUnstable()
        }     

    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                
               script{
                
                    currentBuild.displayName = "qra-${BUILD_NUMBER}${BUILD_ID}"
                    
               }                              
            }
        }
        
        
   stage('Results') {
       
       steps {
//           sh "mkdir -p build/libs" 
//           archiveArtifacts artifacts:''
             sh " mv my-app-1.0-SNAPSHOT.jar 'qra-${BUILD_NUMBER}${BUILD_ID}' "
               }
         }
/*        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
 */    
        
        stage('Upload') {
            
            steps {
                script{
            s3Upload(
                file:'file.txt', 
                bucket:'qraapi', 
                path:'./target/my-app-1.0-SNAPSHOT.jar')
                }

            }
        } 
        
    }
}
