pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-u root'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
 //           args '-v /root/.m2:/root/.m2:z -u root'
            
 
           
        }
    }
        options {
        skipStagesAfterUnstable()
        }     

    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                
               script{
                
                    currentBuild.displayName = "${BUILD_ID}"
                    
               }                              
            }
        }
        
        
   stage('Results') {
       
       steps {

             sh " mv ./target/my-app-1.0-SNAPSHOT.jar 'ali.jar' "
               }
         }
  
        
        stage('buildimage') {
            
            steps {
                script {

                    docker.build("ali-image", ".") 
                 }   
         
                }

            } 
        } 
        
    }


